# Generated by Django 5.1.1 on 2024-09-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_lesson_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='is_paid',
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('enrolled', 'Enrolled'), ('pending', 'Pending'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
