# Generated by Django 5.1.2 on 2024-10-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_course_is_active_remove_enrollment_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='course_images/default_course_image.jpg', null=True, upload_to='course_images/'),
        ),
    ]
