# Generated by Django 5.1.2 on 2024-10-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='course_images/default_course_image.jpeg', null=True, upload_to='course_images/'),
        ),
    ]
