# Generated by Django 5.0.8 on 2024-09-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_lesson_options_remove_lesson_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='published_data',
            new_name='published_date',
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('free', 'Free'), ('paid', 'Paid'), ('subscription', 'Subscription')], default='free', max_length=15),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
